# ===================================================================
# Inception — WordPress (php-fpm) + NGINX (TLS 1.2/1.3) + MariaDB
# - 3 services only
# - HTTPS only (443) exposed to host
# - Data persists under /home/nryser/data/{wordpress,mariadb}
# - Secrets mounted from ../secrets/*
# ===================================================================

networks:
  appnet: {}

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wordpress
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mariadb
      o: bind

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_pass:
    file: ../secrets/credentials.txt
  wp_second_pass:
    file: ../secrets/wp_second_pass.txt

services:
  # ===================== MariaDB =====================
  mariadb:
    image : mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks: [appnet]
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "mariadb -uroot -p\"$(cat /run/secrets/db_root_password)\" -e 'SELECT 1;' >/dev/null 2>&1 || mariadb -uroot -e 'SELECT 1;' >/dev/null 2>&1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  # ================= WordPress (php-fpm) ==============
  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    networks: [appnet]
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_AUTO_INSTALL: ${WP_AUTO_INSTALL:-1}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_SECOND_USER: ${WP_SECOND_USER:-writer42}
      WP_SECOND_EMAIL: ${WP_SECOND_EMAIL:-writer42@example.com}
      WP_SECOND_PASSWORD_FILE: /run/secrets/wp_second_pass
    volumes:
      - wp_data:/var/www/wordpress
    secrets:
      - db_password
      - wp_admin_pass
      - wp_second_pass
    healthcheck:
      # healthy only when FPM cfg parses AND index.php exists (prevents nginx 403)
      test: ["CMD-SHELL", "php-fpm82 -t >/dev/null 2>&1 || exit 1; [ -f /var/www/wordpress/index.php ]"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  # ====================== NGINX =======================
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    restart: unless-stopped
    depends_on:
      wordpress:
        condition: service_healthy
    networks: [appnet]
    ports:
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wp_data:/var/www/wordpress:ro

